version: '3.8'

networks:
  laravel:

# Services
services:
  # Nginx Service
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./src/backend:/var/www/backend
      - ./src:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d           
    depends_on:
      - phpmyadmin
      - backend
      - php
      - frontend    
    networks: 
      - laravel 

  # Backend Service
  backend:
    build:
      context: ./src/backend
      args:
        HOST_UID: $HOST_UID
    working_dir: /var/www/backend
    volumes:
      - ./src/backend:/var/www/backend
    depends_on:
      - mysql
    networks: 
      - laravel

  # PHP Service
  php:
    image: php:8.1-fpm
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks: 
      - laravel
    
   # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "9306:3306"
    environment: 
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_db
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - laravel
    volumes: 
      - ./mysql:/var/lib/mysql   

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks: 
      - laravel

  # Frontend Service
  frontend:
    build: ./src/frontend
    working_dir: /var/www/frontend
    volumes:
      - ./src/frontend:/var/www/frontend
    depends_on:
      - backend
    networks: 
      - laravel
    
  